### PR TITLE
Cleaning Up

### PR DESCRIPTION
**Pull request by spannerman79**
These files are useless "junk" files created by mac, linux and windows

### CODE REVIEW

**Comment by spannerman79** [comment]
Please don't commit this pull yet, cleaning up the junk files still 😛

**Comment by spannerman79** [comment]
Should be good to go.
There are still more extensions to add to gitignore as I am not sure which IDE you use I don't know offhand which extensions should be added (not needed to be in repo)

**Comment by spannerman79** [comment]
Do you use intellij ide? if so please take a moment and read https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

**Comment by AzazeII** [comment]
Thank you for help, and yeah i read that article.

**Pull request closed without merging**
